### ISSUE TITLE
How to take part in hacktober fest 2021: From Zero to Hero

### ISSUE THREAD

**Issue by nitinkumar30** [avinash201199/Python-projects-#14]
I would like to contribute with the steps for completing this fest. I'm also participating for the first time & know the hardships new joiners got. So, would like to eventually help them with complete step-by-step. Is it ok to raise an issue regarding this?

I've gone through various tutorials but many of them were not able to make me understand. After this, I would like to help new joiners in hacktober fest 2021.

Please tag my issue under 'hacktober fest 2021'.

**Comment by avinash201199** [comment]
raise this information in hacktoberfest guide repo , will assign you
